/** Client-safe Agent Teams request, result, and view vocabulary. */

export type {
  CreateTeamTaskRequest,
  RemoteSendTeamMessageRequest,
  RemoteSpawnTeammateRequest,
  SendTeamMessageResult,
  SpawnTeammateResult,
  TeamActivityEntry,
  TeamActivityKind,
  TeamInterruptMutationResult,
  TeamInterruptView,
  TeamMemberEffort,
  TeamMemberView,
  TeamMessageMutationResult,
  TeamSpawnMutationResult,
  TeamTailKind,
  TeamTailLine,
  TeamTaskAction,
  TeamTaskId,
  TeamTaskMutationResult,
  TeamTaskStatus,
  TeamTaskView,
  TeamView,
  TeamWaitResult,
  UpdateTeamTaskRequest,
} from './types.ts'
